### ISSUE TITLE
variants genomic coordinate and HGVS doesn't match. e.g. NM_007294.3:c.181T>G

### ISSUE THREAD

**Issue by MollyZhang** [BD2KGenomics/brca-pipeline#158]

**Comment by melissacline** [comment]
Is the issue that the variant is identified as "NM_007294:c.181T>G" but the reference and alt alleles are A and C respectively?  If so, then that actually makes sense.  BRCA1 is on the minus strand.  The HGVS string represents the transcript-level change, as transcribed from the minus strand.  The VCF follows the convention of using the equivalent bases on the plus strand, wich replaces the T with an A and the G with a C.  Or, is the question different?

**Comment by MollyZhang** [comment]
Yes you are right. This issue can be closed.
