### ISSUE TITLE
deal with variants with the format of chrx:123:A>A

### ISSUE THREAD

**Issue by MollyZhang** [BD2KGenomics/brca-pipeline#160]
such as this variant line:
genome coordinate: chr13:32332592:A>A|chr13:32333274:C>C|chr13:32340868:G>G|chr13:32338918:A>A|chr13:32355250:T>T

**Comment by melissacline** [comment]
Sent email to Sam Baxter asking for clarification.

**Comment by maryjgoldman** [comment]
Sam says this is just bad data

**Comment by maryjgoldman** [comment]
We are going to remove these and keep a log of them.
